default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  port: 5432
  pool: 5
#  user: cfp

development:
  <<: *default
  database: cfp_development

test: &test
  <<: *default
  database: cfp_test
