default:
  adapter: postgresql
  encoding: utf8
  host: localhost
  port: 5432
  pool: 5
#  user: cfp

development: &development
  adapter: sqlite3
  database: db/cfp_development.sqlite3
  pool: 5
  timeout: 5000

test: &test
  <<: *development
  database: cfp_test
